name: FaceofMind
description: "A Mobile Based Application for Mental Health Awareness."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  fluttertoast: ^8.2.4
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  url_launcher: ^6.2.5
  speech_to_text: ^7.1.0
  flutter_tts: ^3.8.2
  permission_handler: ^11.3.0
  flutter_dotenv: ^5.1.0
  google_ml_kit: ^0.20.0
  google_mlkit_barcode_scanning: ^0.14.1
  google_mlkit_commons: ^0.11.0
  google_mlkit_digital_ink_recognition: ^0.14.1
  google_mlkit_entity_extraction: ^0.15.1
  google_mlkit_face_detection: ^0.13.1
  google_mlkit_face_mesh_detection: ^0.4.1
  google_mlkit_image_labeling: ^0.14.1
  google_mlkit_language_id: ^0.13.0
  google_mlkit_object_detection: ^0.15.0
  google_mlkit_pose_detection: ^0.14.0
  google_mlkit_selfie_segmentation: ^0.10.0
  google_mlkit_smart_reply: ^0.13.0
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_translation: ^0.13.0
  camera: ^0.10.5+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/images/Logo.png
    - assets/images/qrcodegcash.png
    - assets/model.tflite
    - assets/emotion_labels.txt

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Logo.png"
  min_sdk_android: 21
  min_sdk_ios: 13
  prefix: "Icon"

flutter_native_splash:
  image: assets/images/Logo.png
  color: "#ffffff"
  android: true
  ios: true