# Generated by Django 5.2.3 on 2025-07-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0002_alter_communitycomment_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voicedata',
            name='audio_path',
        ),
        migrations.AddField(
            model_name='wellnesssuggestion',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
